### PR TITLE
Update Readme to include in-app review info

### PR DESCRIPTION
**Pull request by AntvissMedia**

### CODE REVIEW

**Comment by saamerm** [comment]
@AntvissMedia could you please add examples possibly for the features?

**Comment by AntvissMedia** [comment]
do you mean screenshots? 

as far as implementation goes, the sample pretty much covers it, does it not? I don't think it gets much easier to understand than that!

I've added a bit more information and i've styled the Readme file to make it easier to read/understand.

**Comment by saamerm** [comment]
@AntvissMedia yeah screenshots would be nice! Also, something like this "[How to use it" section](https://github.com/sthewissen/Xamarin.Forms.PancakeView/wiki/Setup#how-to-use-it) would help.

We can avoid users from going through 3 different files from the README to understand the implementation

**Comment by AntvissMedia** [comment]
I see what you're saying, but it's best to avoid sounding like we say "there's only one way to implement this - our way!" as that will open the door for issues being open from people who aren't able to implement it like we say they should. 

At it's "core" (excuse the pun), this is a library binding which allows people to implement certain features as they see fit. If there was only one way to implement the bindings, we probably would've abstracted that and packaged it with the bindings.

There is an known working and tested example of implementation which devs can follow and even improve upon, but I think it's important that we don't say this is the only way it can be implemented.

I hope I make sense, but please don't hesitate to correct me.

**Comment by saamerm** [comment]
Hmm yeah I see your point. I agree. I think screenshots would be great at least to explain what it looks like after they have implemented the code in their way

**Comment by AntvissMedia** [comment]
Agreed! @PatGet have you got any screenshots of the In-App Update feature in action following your implementation so it can be added to the Readme?

**Comment by PatGet** [comment]
@AntvissMedia you can find two Screenshots here : https://1drv.ms/f/s!AlWQxCMzJ70duJYGigTn94HfaJosIA

**Comment by PatGet** [comment]
@AntvissMedia when you update with screenshots, can you please also update the Nuget Version?

**Comment by AntvissMedia** [comment]
@PatGet Thank you for the screenshots. I have added them and updated the package version in the badge. My apologies for all the silly commits beforehand. Had a brain-fart! 😃

**Pull request merged**
