### PR TITLE
Some ammendments with documentation. The update loop will occur when …

### PR DESCRIPTION
**Pull request by gabrieldwight**
…you check for updates in the onresume method. I put the updatemanager in the oncreate method. You can test it further by tryting to send an update from the close track in play store.

### CODE REVIEW

**Comment by PatGet** [comment]
@gabrieldwight Still get the Loop, i pushed a new APK to the store to ensure that it is not a problem with the APK itself. Code with comments looks good, seems like you created the best available documentation on that topic.

**Comment by gabrieldwight** [comment]
@PatGet Can you try to build another test app using xamarin Android Native to see if it will produce the update loop. On my side I used the xamarin android native to test the play core and did not experience an update loop. As I try to find a solution for the xamarin form using the platform specific binding library.

**Comment by PatGet** [comment]
@gabrieldwight Oh my...! I tried your suggested option of creating a android only app and while I created the the Play Store Entry i came across the "Let Google manage and protect your app signing key" option which is now default. See https://support.google.com/googleplay/android-developer/answer/7384423 for more Info. 

Basically while I used the same KEYSTORE in Visual Studio that I used for uploading to the Store, Google uses that Signature to verify the APK but than signs it again. 

Found that in the adblog:
`Finsky  : [1534] olc.run(4): Error committing session: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package de.patget.playtest signatures do not match previously installed version; ignoring!`

**Comment by PatGet** [comment]
Just uploaded a new Version to the Store, disabled automatic Updates in my Play Store app and now had a successful In-App Update. Works like a charme!

**Comment by gabrieldwight** [comment]
> @gabrieldwight Oh my...! I tried your suggested option of creating a android only app and while I created the the Play Store Entry i came across the "Let Google manage and protect your app signing key" option which is now default. See https://support.google.com/googleplay/android-developer/answer/7384423 for more Info.
> 
> Basically while I used the same KEYSTORE in Visual Studio that I used for uploading to the Store, Google uses that Signature to verify the APK but than signs it again.
> 
> Found that in the adblog:
> `Finsky : [1534] olc.run(4): Error committing session: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package de.patget.playtest signatures do not match previously installed version; ignoring!`

Thanks for the information. So it means the app installed must have the same matching KEYSTORE signature that was used for the Google Play App Signing process.

That's Good News to hear that the in-app update now works with no issues.

**Pull request merged**
